# -*- coding: utf-8 -*-
"""Pertemuan 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_A2Lgm9xL-MB2JU7JYBNN8tuy_Z5_X3e
"""

import numpy as np
 import matplotlib.pyplot as plt

 arr = np.random.randint(256,size=(500,500))
 plt.imshow(arr,cmap = plt.cm.gray) #nilai rgb dianggap sama

arr2 = arr +  100
plt.imshow(arr2,cmap = plt.cm.gray,vmin=0,vmax=255) #rescel berapapun nilainya hasilnya akan retan di 0 -255

from skimage.color import rgb2gray #ubah rgb ke grayscale

img = plt.imread("panda.jpg")
plt.imshow(img)

from skimage.color import rgb2gray #ubah rgb ke grayscale

img_g = rgb2gray(img)*255
plt.imshow(img_g,cmap = plt.cm.gray)

img_g2 = img_g + 100
print(img_g2.shape)
plt.imshow(img_g2,cmap = plt.cm.gray,vmin = 0,vmax = 255)

plt.imshow(img +100)

"""# **Latihan**"""

import matplotlib.pyplot as plt
import numpy as np
from skimage.color import rgb2gray

def quantization(img) :
  img_q = np.zeros((img.shape[0],img.shape[1]))
  for r in range(0,img.shape[0]):
    for c in range (0,img.shape[1]):
      if img[r,c] < 100:
        img_q[r,c]= 50
      elif img[r,c] >200:
        img_q[r,c] = 230
      else:
        img_q[r,c] = 150

  return img_q

img = plt.imread("alam.jfif")
img_gray = rgb2gray(img)*255
img_quant = quantization(img_gray)

# plt.figure()
# plt.imshow(img)
# plt.figure()
# plt.imshow(img_gray,cmap=plt.cm.gray)
# plt.figure()
plt.imshow(img_quant,cmap=plt.cm.gray,vmin=0, vmax=255)

import matplotlib.pyplot as plt
from skimage.color import gray2rgb

