# -*- coding: utf-8 -*-
"""Pertemuan 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tJX3Q73eriYMftLRrtB0HNBpI0xNsVYM
"""

import matplotlib.pyplot as plt

img = [[100]] 

plt.imshow(img,cmap=plt.cm.gray)
#f(x,y)=I Grayscale 0-255

img = [[100,54,2,45]] 

plt.imshow(img,cmap=plt.cm.gray)
#f(x,y)=I Grayscale 0-255

img = [[200,54,2,45],
       [56,99,32,178]] 

plt.imshow(img,cmap=plt.cm.gray)

img = [[200,54,2,45],
       [56,99,32,178]] 

plt.axis('off')#untuk menghilangkan sampling
plt.imshow(img,cmap=plt.cm.gray)
plt.savefig('gambar.png') #untuk mengubah hasil running dan disimpan dalam png

img = [[200,54,2,45],
       [56,99,32,178]] 

plt.axis('off')#untuk menghilangkan sampling
plt.imshow(img,cmap=plt.cm.gray)
# plt.savefig('gambar.png') #untuk mengubah hasil running dan disimpan dalam png
plt.imsave('gambar.png',arr=img,cmap='gray')
#kalau ingin dimasukan dalam grayscale di masukan cmap/colormappingnya

logojpg= plt.imread('logo.jpg')
plt.imshow(logojpg)
print(logojpg.shape)
print(logojpg)

logopng= plt.imread('logo2.png')
plt.imshow(logopng)
print(logopng.shape)
print(logopng)

"""1 semster =matriks grayscale
binary
RGB
"""